#!/usr/bin/env bash

DB_NAME="magento2"
DB_USER="magento2"
DB_PASS="!magento2"

MYSQL="mysql"

echo "===[CREATE DATABASE]==="

$MYSQL -e "CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS';"
$MYSQL -e "GRANT USAGE ON * . * TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;"
$MYSQL -e "CREATE DATABASE IF NOT EXISTS $DB_NAME ;"
$MYSQL -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'%' WITH GRANT OPTION ;"

echo ""
